default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRESQL_USERNAME") %>
  password: <%= ENV.fetch("POSTGRESQL_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRESQL_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRESQL_PORT", 5432) %>

development:
  <<: *default
  database: space_system_api_development

test:
  <<: *default
  database: space_system_api_test

production:
  <<: *default
  database: space_system_api_production
